<% env = ENV.fetch("RAILS_ENV", ENV.fetch("RACK_ENV", "development")) %>

:concurrency: 5

:queues:
  - ["<%= env %>_default", 5]
  - ["<%= env %>_imports", 5]
  - ["<%= env %>_exports", 3]
  - ["<%= env %>_mailers", 2]
